### ISSUE TITLE
Authentication succeeds for users with incorrect passwords

### ISSUE THREAD

**Issue by davidjb** [kvspb/nginx-auth-ldap#40]
I'm using Nginx 1.4.6 and the latest version of this module, and noticing that passwords appear to not be being validated.

Password validation is correct when using a config like:

```
ldap_server local {
    url ldaps://ldap.example.org/ou=Users,dc=example,dc=org?uid?sub?(objectClass=person);
    require valid_user;
}
```

An attempt to use a valid account with a false password fails (re-asking for authentication with a 401), and a valid account with a correct password succeeds.

If I use this, however, authentication succeeds for a user matching the given conditions, but no password validation is applied:

```
ldap_server local {
    url ldaps://ldap.example.org/ou=Users,dc=example,dc=org?uid?sub?(objectClass=person);
    group_attribute "uniqueMember";
    group_attribute_is_dn on;
    require user 'uid=user1,ou=Users,dc=example,dc=org';
    require user 'uid=user2,ou=Users,dc=example,dc=org';
    require group 'cn=myorg,ou=groups,dc=example,dc=org';
    satisfy any;
}
```

Auth succeeds if the user ID in a request is set as either `user1`, `user2`, a user that's part of the given group, but it **succeeds** with the password set as **anything**.  Auth fails, however, if say `user3` is attempted, seemingly because the user fails to match the `require` statements.

I'm not yet running a recompiled Nginx with debug enabled, but I will shortly.  No errors or the like appear in the console output for a non-daemon Nginx compiled normally.

**Comment by manas86** [comment]
hi @davidjb 

 I will appreciate any direction towards the solving and assist me to reach the goal for centos7.
I'm following and using https://github.com/kvspb/nginx-auth-ldap . So my docker file looks like this.
RUN cd ~ \
&& git clone https://github.com/kvspb/nginx-auth-ldap \
&& git clone https://github.com/nginx/nginx \
&& cd /root/nginx \
&& /root/nginx/auto/configure \
--add-module=/root/nginx-auth-ldap \
--with-http_ssl_module \
--with-debug \
--conf-path=/etc/nginx/nginx.conf \
--sbin-path=/usr/sbin/nginx \
--pid-path=/var/log/nginx/nginx.pid \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--with-stream \
--with-stream_ssl_module \
--with-debug \
--with-file-aio \
--with-threads \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_v2_module \
--with-http_auth_request_module \
&& make install \
&& cd .. \
&& rm -rf nginx-auth-ldap \
&& rm -rf nginx
now i have difficulty in setting of nginx.conf, basically what I want to achieve is as soon as the login window pop up users will give their own credentials including user name and password which will eventually validated against LDAP container (CN=devops,OU=project,OU=services,OU=groups,o=orgname). So that means I can't have the password stored in my config file. Can you help me to build the setup ?
at this moment, I setup my config file like this, which I doubt it will work
under http tag:
ldap_server ldap {
url "ldaps://XXXX:636/ou=people,o=orgname?uid?(objectclass=person);"
  require valid_user;"
# group attribute name which contains member object
group_attribute member;
# search for full DN in member object
group_attribute_is_dn on;
# matching algorithm (any / all)
satisfy any;
require user "CN=devops,OU=project,OU=services,OU=groups,o=myorg"; 
}
and in location tag
location / {
#auth_basic "Restricted Content";
#auth_basic_user_file /etc/nginx/pass/.htpasswd;
auth_ldap "Closed content";
auth_ldap_servers ldap;
root html;
index index.html index.htm;
}
how can I do this ?
Regards,
Manas

**Comment by davidjb** [comment]
@manas86 As that's a support request, best to put this on StackOverflow or similar where someone can assist you.
